trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UniversalPackages@0
  displayName: 'Conectar y publicar Calculadora en el Feed'
  inputs:
    command: 'publish'
    publishDirectory: '$(Calculadora)' # <-- Modificamos esto para que tome la raíz de tu GitHub
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Presentación Análisis de sistemas 2/Prueba1' # (Si en el paso anterior le pusiste el nombre del proyecto, déjalo aquí también)
    vstsFeedPackagePublish: 'paquete-calculadora' 
    versionOption: 'custom'       # <-- Cambiamos la forma de versionar
    versionPublish: '1.0.1'       # <-- Declaramos que esta es la versión oficial 1.0.0