trigger:
- main 

pool:
  # Cambiamos a Windows para evitar que las tildes del proyecto rompan la consola
  vmImage: 'windows-latest' 

steps:
- task: UniversalPackages@0
  displayName: 'Publicar Calculadora a Artifacts'
  inputs:
    command: 'publish'
    publishDirectory: '$(Calculadora)' 
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Prueba1.1' # Al ser de organización, ya no necesita el nombre del proyecto
    vstsFeedPackagePublish: 'paquete-calculadora' 
    versionOption: 'custom'       
    versionPublish: '1.0.0'